version: "3.9"

services:
  web:
    image: nginx:1.27-alpine
    container_name: web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB:-laravel}
      DB_USERNAME: ${POSTGRES_USER:-laravel}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    depends_on:
      - db

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node
    user: root 
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_DEV_SERVER_URL: "http://localhost:5173"
    depends_on:
      - app

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-laravel}
      POSTGRES_USER: ${POSTGRES_USER:-laravel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "54321:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
  node_modules: